# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, comonad, distributive, doctest, failure, filepath, hspec
, hspecExpectations, keys, lens, linear, mtl, numbers, parsers
, PSQueue, QuickCheck, semigroupoids, semigroups, split, text
, thyme, transformers, trifecta
}:

cabal.mkDerivation (self: {
  pname = "commodities";
  version = "0.2.0";
  src = ./.;
  buildDepends = [
    comonad distributive failure keys lens linear mtl numbers parsers
    PSQueue semigroupoids semigroups split text thyme transformers
    trifecta
  ];
  testDepends = [
    doctest filepath hspec hspecExpectations lens QuickCheck semigroups
    thyme transformers
  ];
  meta = {
    description = "Library for working with commoditized amounts and price histories";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
